name: "Deploy Assets"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm install
    - run: npm run build
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - run: pip install awscli
    - run:
        aws s3 cp JD-FullStack-Engineer/solution/client/dist/app.js s3://joyn-assets/app.js
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}





