name: CD

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Load environment variables from .env file
      run: |
        cat .env | grep -v '#' | while read line; do echo "$line" >> $GITHUB_ENV; done

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_HUB_USERNAME }}
        password: ${{ env.DOCKER_HUB_PASSWORD }}

    - name: Build and push Backend image
      run: |
        docker build -t ${{ env.DOCKER_HUB_USERNAME }}/backend:latest ./JD-FullStack-Engineer/backend
        docker push ${{ env.DOCKER_HUB_USERNAME }}/backend:latest

    - name: Build and push Client image
      run: |
        docker build -t ${{ env.DOCKER_HUB_USERNAME }}/client:latest ./JD-FullStack-Engineer/client
        docker push ${{ env.DOCKER_HUB_USERNAME }}/client:latest

    - name: Deploy to AWS EC2
      env:
        SSH_PRIVATE_KEY: ${{ env.SSH_PRIVATE_KEY }}
        EC2_HOST: ${{ env.EC2_HOST }}
      run: |
        mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
        ssh-keyscan ubuntu@$EC2_HOST >> ~/.ssh/known_hosts
        eval $(ssh-agent)
        ssh-add secrets/id_rsa
        ssh -i secrets/id_rsa -o UserKnownHostsFile=/github/home/.ssh/known_hosts -tt ubuntu@$EC2_HOST "echo test > testfile1"
          docker pull ${{ env.DOCKER_HUB_USERNAME }}/backend:latest
          docker pull ${{ env.DOCKER_HUB_USERNAME }}/client:latest
          docker-compose down
          docker-compose up -d
