name: CD

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Load environment variables from .env file
      run: |
        cat .env | grep -v '#' | while read line; do echo "$line" >> $GITHUB_ENV; done

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_HUB_USERNAME }}
        password: ${{ env.DOCKER_HUB_PASSWORD }}


    - name: Deploy to AWS EC2
      env:
        SSH_PRIVATE_KEY: ${{ env.SSH_PRIVATE_KEY }}
        EC2_HOST: ${{ env.EC2_HOST }}
      run: |
        chmod 600 secrets/id_rsa
        ssh -o StrictHostKeyChecking=no -tt -i secrets/id_rsa $EC2_HOST  << EOF
        docker pull ${{ env.DOCKER_HUB_USERNAME }}/backend:latest
        docker pull ${{ env.DOCKER_HUB_USERNAME }}/client:latest
        docker pull ${{ env.DOCKER_HUB_USERNAME }}/database:latest
        sudo docker run -d ${{ env.DOCKER_HUB_USERNAME }}/database
        sudo docker run -d  ${{ env.DOCKER_HUB_USERNAME }}/client
        sudo docker run -d  ${{ env.DOCKER_HUB_USERNAME }}/backend
        EOF
