name: "JD-Fullstack Workflow"
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: A job that only deploys a ReactJS app to s3
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy_assets
